import { Metadata } from "next";
import "@/app/globals.css";
import { WalletProvider } from "@/components/wallet-provider";
import { StarknetProvider } from "@/components/starknet-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#00031B] text-[#EAEDE7]">
        <StarknetProvider>
          <WalletProvider>{children}</WalletProvider>
        </StarknetProvider>
      </body>
    </html>
  );
}
