name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [main, develop]
  pull_request:
    paths:
      - 'backend/**'
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1  
        with:
          version: '1.5.1'
      
      - name: Install dependencies
        run: poetry install --no-root
      
      - name: Run Black
        run: poetry run black --check backend/
      
      - name: Run Flake8
        run: poetry run flake8 backend/
      
      - name: Run pytest
        run: poetry run pytest backend/