name: Contracts CI

on:
  push:
    paths:
      - 'contracts/**'   # Only trigger when contracts change
    branches: [main, develop]
  pull_request:
    paths:
      - 'contracts/**'
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # Updated to v4 (latest)
      
      # Install Scarb (Cairo package manager)
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"   # Pinned version
      
      # Install Starknet Foundry (snforge)
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.39.0"   # Pinned version
      
      # Verify installations
      - name: Check Versions
        run: |
          scarb --version
          snforge -V
      
      # Format check (similar to Rust's `cargo fmt`)
      - name: Format Check
        run: scarb fmt --check
      
      # Run Starknet tests
      - name: Run Tests
        run: snforge test
      
      # Build the project (compile Cairo code)
      - name: Build Project
        run: scarb build