name: Contracts CI

on:
  push:
    paths:
      - 'contracts/**'  
    branches: [main, develop]
  pull_request:
    paths:
      - 'contracts/**'
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts  
    steps:
      - uses: actions/checkout@v4   
      
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"   
     
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.39.0"   
      
      
      - name: Check Versions
        run: |
          scarb --version
          snforge -V
      
      
      - name: Format Check
        run: scarb fmt --check
      
  
      - name: Run Tests
        run: snforge test
      
      - name: Build Project
        run: scarb build